"""Seed-pair generation strategies for `mepd channels`: given a fixed
(start, end) pair, produce per-endpoint candidate pools to pair up and run
MSMEP on, so recursive splitting can be given more than one starting guess
to discover distinct TS channels between the same two molecules, instead of
just whichever single geometry was given.

`conformers` (RDKit or CREST conformer sampling of each endpoint) is the only
implemented method today. A future method (e.g. alternate interpolation
seeds, GSM restart perturbations) just adds another branch here returning
the same `(start_pool, end_pool)` shape -- pairing, MSMEP execution, and
classification in `cli.py` are all method-agnostic.
"""
from __future__ import annotations

from mepd.conformers import ConformerInputs
from mepd.nodes.node import StructureNode


def generate_seed_pairs(
    method: str,
    start_node: StructureNode,
    end_node: StructureNode,
    *,
    conformer_inputs: ConformerInputs | None = None,
    stats: dict | None = None,
) -> tuple[list[StructureNode], list[StructureNode]]:
    """Return `(start_pool, end_pool)`: candidate structures for each
    endpoint, generated by `method`. All-to-all pairing across the two
    pools is the caller's responsibility. If `stats` is given, per-endpoint
    generation stats land in `stats["start"]` / `stats["end"]`."""
    if method == "conformers":
        from mepd.conformers import generate_conformers

        stats = stats if stats is not None else {}
        stats["start"], stats["end"] = {}, {}
        return (
            generate_conformers(start_node, conformer_inputs, stats["start"]),
            generate_conformers(end_node, conformer_inputs, stats["end"]),
        )
    raise ValueError(f"Unknown sampling method '{method}'. Known: 'conformers'.")
